= DevOps workflow notes
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== Phases description

=== PLAN

La phase de planification / conception concerne tout ce qui a lieu AVANT que l'équipe de développement ne débute l'écriture du code. +
C'est le moment où l'on va construire la roadmap produit afin de guider les développements à venir.

Cette roadmap est généralement enregistrée et suivie à l'aide d'un *outil de gestion de projet* comme Jira, Trello, Azure DevOps (fonctionnalité "Boards"), etc.

=== CODE

C'est durant cette phase que l'équipe de développement implémente les stories de la roadmap produit, et donc "écrit le code".

Pour ce faire, les développeurs utilisent un ensemble d'outils (IDE et leurs plugins, outil de modélisation, utilitaires divers, etc.), langages de développement (Java, Python, etc.), frameworks (Spring, Hibernate, etc.), librairies (Guava, Apache Commons, etc.) et spécifications (JAX-RS, CDI, JSON-P, etc.), pour certains définis au niveau de l'organisation, pour d'autres spécifiques au projet.

Une fois écrit, le code doit être sauvegardé et partagé dans l'équipe à l'aide de solutions d'hébergement de code (*Source Code Repository Manager*) s'appuyant sur un logiciel de *SCM* (*Source Code Management*). +
*Git* est actuellement le SCM le plus utilisé au monde, et parmi les repo manager populaires s'appuyant dessus nous trouvons aujourd'hui GitHub, GitLab, Bitbucket pour ne citer qu'eux.

==== Ressources 

* *Git branching strategy* : 
    ** feature branching (Gitflow, GitHub flow ou GitLab flow) vs trunk-based development : 
        *** https://dzone.com/articles/why-i-prefer-trunk-based-development-over-feature
        *** 2022 : https://nira.com/git-branching-strategies-vs-trunk-based-development/ 
        *** https://hitesh-pattanayak.medium.com/git-flow-development-vs-trunk-based-debelopment-923ce4553043
            **** je cite cet article avant tout pour son bon schéma de comparaison des 2 stratégies (simple et efficace)
            **** en fait, on retrouve ces schémas dans cet article de Medium (2018) : +
            https://medium.com/safetycultureengineering/trunks-are-not-just-for-trees-from-git-flow-to-trunk-based-development-949d580697ef
            **** mais en fait, ils viennent initialement de cet article de Microsoft : +
            https://blogs.technet.microsoft.com/devops/2016/06/21/a-git-workflow-for-continuous-delivery
            **** très très bon REX du Git flow, de ses écueils, et des raisons du retour au trunk-based development
        *** https://dzone.com/articles/why-i-prefer-trunk-based-development-over-feature
            **** bon (vieux) schéma du trunk-based development

    ** Depuis quelques années maintenant, le *trunk-based development* est redevenu la stratégie de branching la plus utilisée, devant le feature branching qui avait pris le lead lors de l'adoption massive des outils de type DVCS (basés sur Git).
        *** Principalement du fait de difficultés de merge rencontrées avec le feature branching du fait du grand nombre de branches manipulées ("feature branches hell")

=== BUILD

La phase de BUILD est celle où le code source va être récupéré (du précédent repo manager) puis buildé afin de pouvoir être testé.

Le résultat du build, souvent appelé « archive » (JAR pour Java ARchive, WAR pour Web ARchive, etc.), a pour vocation d'être ensuite déployé, testé et validé dans les différents environnements du projet (par exemple DEVELOPPEMENT, INTEGRATION, RECETTE, PRE-PRODUCTION et finalement PRODUCTION).

 	Il est à noter que l'on devrait toujours ne builder qu'une unique fois une archive, puis déployer et tester progressivement cette même archive dans les différents environnements et NON builder une archive spécifique par environnement

La création de l'archive à partir du code source est réalisée à l'aide d'un outil de build.
Parmi les plus connus on retrouve Maven, Gradle, Ant, NPM, etc.

Le déclenchement du build est généralement réalisé par un outil d'automatisation, de type serveur d'intégration continue. 
L'élément déclencheur du build (« trigger ») est soit une action manuelle, soit la détection en temps presque réel d'une modification du code dans le repo manager (présence d'un nouveau commit modifiant le code).
Les serveurs d'intégration délègue ensuite la création de l'archive aux outils de build vus précédemment.
Parmi les serveurs d'intégration continue les plus connus on retrouve Jenkins, Travis CI, GitLab CI, Azure DevOps, etc.

* Rappel sur quelques formats d'archive : 
    ** https://objis.com/comprendre-les-livraisons-j2ee-war-jars-rar-ear/
    ** https://www.theserverside.com/feature/What-are-the-differences-between-EAR-JAR-and-WAR-files

* alternatives à Jenkins en 2022 : 
    ** https://www.capterra.fr/alternatives/171026/jenkins
    ** Travis CI, CircleCI, TeamCity, etc.
* Pour une définion de Jenkins mentionnant le concept de "automation", voir : +
https://www.techtarget.com/searchsoftwarequality/definition/Jenkins
    ** Jenkins est considéré comme une automation platform, un serveur d'intégration continue, un scheduler et peu également être utilisé comme ordonnanceur en le "tordant un peu"
        *** Pour un véritable ordonnanceur, partir plutôt sur une solution de type Autosys, ou Control-M.
        *** Pour ces derniers outils, on parlera davantage d'*orchestration* du flux de travail (il est souvent question de "workload automation", on pourra également parler d'orchestrateur de workflow): +
        "Control‑M simplifies and automates diverse *batch application workloads* while reducing failure rates, improving SLAs, and accelerating application deployment."
* Pour un exemple de workflow Jenkins : 
    ** https://www.jenkins.io/pipeline/getting-started-pipelines/
    ** https://www.jenkins.io/doc/book/pipeline/
    ** très bon schéma, classique et clair, en 7:47 dans cette vidéo : +
    https://youtu.be/8lGoul8KUdQ?t=467[Understanding DevOps using Jenkins, Maven, Nexus Artifactory and Ansible]
* Cas d'usage de Jenkins pour des workflows allant jusqu'à la production : 
    ** https://medium.com/@maxy_ermayank/pipeline-as-a-code-using-jenkins-2-aa872c6ecdce

* Alternatives à Maven et autres build tools : 
    ** https://alternativeto.net/software/gradle/
    ** Maven, Gradle, Ant, SBT
    ** NPM pour Node.js
        *** voir https://devstory.net/11925/qu-est-ce-que-npm

=== TEST

----
Une fois buildés, les archives sont déployés dans un environnement de qualification où plusieurs séries de tests, manuels (UAT ou tests de recette) et / ou automatiques (tests d'intégration, d'API, de sécurité, etc.) sont déroulés.
Les archives peuvent également être déployées dans plusieurs environnements de qualification, chacun étant l'objet de tests de natures différentes.
----

* Pyramide des tests : https://latavernedutesteur.fr/2022/02/07/pourquoi-une-pyramide-pour-les-tests/

=== RELEASE

----
La phase de release est celle où le livrable de production (certains outils parleront de « package » ou « deployment package ») va être créé en combinant les archives précédemment buildées et testées avec les différents paramètres permettant de les dédier à l'environnement ciblé (package = archives + fichiers de paramétrage).

Le livrable de production / package ainsi créé sera ensuite stocké dans un référentiel spécifique. 
Suivant la nature du livrable, ce référentiel pourra être soit un repository manager (Nexus et Artifactory sont les plus utilisés), ou outil dédié (XL Deploy (maintenant Digital.ai Deploy)
----

* semantic versioning pour les release
    ** https://code-garage.fr/blog/qu-est-ce-que-le-semantic-versioning/

=== DEPLOY

----
La phase de DEPLOY correspond au déploiement, à l'installation du livrable de production de la phase RELEASE en environnement de PROD.
Ce déploiement peut être soit manuel dans le cadre d'une approche Continuous Delivery, soit automatique dans le cadre du Continuous Deployment.

Les principaux outils permettant de configurer un environnement à partir des éléments contenus dans le livrable de production sont appelés outils d'automatisation et de gestion de configuration, parmi lesquels on peut citer Ansible, XL Deploy (Digital.ai Deploy), Terraform.
Ces outils permettent d'automatiser totalement la procédure de déploiement qui est décrite sous forme de fichier (descripteur de déploiement), on parlera d'Infrastructure-as-Code (IaC)

Et, plutôt que de déployer un livrable sur un serveur physique, les solutions de virtualisation et conteneurisation sont plébiscitées.
Ces dernières, conjuguées à l'Infrastrucuture-as-Code, permettent une meilleure agilité et scalabilité (capacité à détruire, recréer et ajouter au besoin un ou plusieurs runtime / environnements), des caractéristiques très demandées pour les architectures Cloud et microservices qui multiplient le nombre de serveurs et services.
Parmi les solutions de virtualisation et de conteneurisation les plus connues : toutes les stacks Cloud actuelles, Docker, Podman, Kubernetes, OpenShift, etc.
----

* Définition claire du but d'Ansible : https://blog.stephane-robert.info/post/introduction-ansible/
* Pour les autres outils d'automatisation et gestion de configuration les plus utilisés en 2022, voir https://www.servertribe.com/top-5-ansible-alternatives/
    ** En gros, Terraform, Puppet, Chef

=== OPERATE

* outils d'alerting les plus utilisés en 2022 : https://www.g2.com/categories/it-alerting
+
--
*IT alerting software* delivers notifications for *IT systems failures*. These tools will monitor systems for poor performance, infrastructure issues, and other IT management issues. These notifications may be delivered via email, SMS, or other means of communication. Companies use these tools to identify issues within their networks, IT infrastructure, and other IT systems to reduce downtime and prevent potential permanent damage.
--

* Très bon article sur OpenTelemetry, l'observabilité, les logs / métriques / traces : 
https://www.splunk.com/fr_fr/data-insider/what-is-opentelemetry.html
    ** OpenTelemetry : OpenTelemetry sera à terme le cadre d'observabilité dominant dans le paysage de télémétrie natif du cloud.

* Prometheus : https://prometheus.io/docs/introduction/overview/
    ** "Prometheus is an open-source systems monitoring and alerting toolkit originally built at SoundCloud."
    ** "Prometheus collects and stores its metrics as time series data, i.e. metrics information is stored with the timestamp at which it was recorded, alongside optional key-value pairs called labels."

* Definition of *alerting and monitoring* : https://www.oreilly.com/library/view/effective-monitoring-and/9781449333515/ch01.html (TRES BON)
    ** contient également une bonne définition d'un *monitoring system* : +
    "A set of software components used for data collection, their processing, and presentation is called a monitoring system.""
    
    ** Différence entre monitoring et alerting : 

        *** *MONITORING* (proactive monitoring) : +
        "The former involves watching visual indicators, such as timeseries and dashboards, and is sometimes what administrators mean by monitoring." +
        "Monitoring is the *process of maintaining surveillance over the existence and magnitude of state change* and data flow in a system. Monitoring aims to identify faults and assist in their subsequent elimination. The techniques used in monitoring of information systems intersect the fields of real-time processing, statistics, and data analysis. A set of software components used for data collection, their processing, and presentation is called a *monitoring system*."

        *** *ALERTING* (reactive monitoring) : +
        "involves automated ways to deliver notifications to operators in order to bring to their attention a grave change in system's state; this is usually referred to as alerting." +
        "Alerting is the *capability of a monitoring system to detect and notify the operators about meaningful events that denote a grave change of state*. The notification is referred to as an alert and is a simple message that may take multiple forms: email, SMS, instant message (IM), or a phone call. The alert is passed on to the appropriate recipient, that is, a party responsible for dealing with the event. The alert is often logged in the form of a ticket in an *Issue Tracking System* (ITS), also referred to simply as *ticketing system*."

            **** Definition of an *alert* : +
            "An alert is a *notification of a potential problem*, which can take one or more of the following forms: email, SMS, phone call, or a ticket. An alert is issued by an alarm when the system transitions through some threshold, and this threshold breach is detected by a monitor. Thus, for example, you may configure an alarm to alert you when the system exceeds 80% of CPU utilization for a continuous period of 10 minutes." +
            "A notification message informing about a change of state, typically signifying a potential problem."

    ** On ne peut PAS avoir d'alerting sans monitoring

* Pour les ITS et outils de ticketing (bug reporting) : https://teambrain.fr/optimisez-votre-ticketing/
    ** JIRA, ServiceNow, Mantis, etc.

* Les systèmes de monitoring sont souvent regroupés en sous-catégories suivant leur spécialité. +
Voici quelques exemples : 
    ** les APM (Application Performance Management) : Dynatrace et Datadog
        *** https://www.g2.com/categories/it-alerting
    ** logiciel de supervision : Centreon, Sentry, Nagios
        *** voir https://www.lemagit.fr/definition/Surveillance-IT-IT-monitoring
    ** Prometheus pour le monitoring de Kubernetes
        *** https://prometheus.io/docs/introduction/overview/
    ** OpenTelemetry devient de plus en plus la norme pour l'envoi et la collecte de données de télémétrie

* Systèmes de monitoring : 
    ** https://intellipaat.com/blog/devops-monitoring-tools/
    ** https://www.g2.com/categories/it-alerting

* Pour un exemple d'article qui met Centreon et Prometheus au même niveau, en tant que "outils de monitoring", voir : https://stackshare.io/stackups/centreon-vs-prometheus

=== FEEDBACK & MONITORING

* Monitoring and alerting : https://www.oreilly.com/library/view/effective-monitoring-and/9781449333515/ch01.html
    ** Monitoring "refers to the process of becoming aware of the state of a system"
    ** il y est question de la "*Monitoring's feedback loop*" : +
    "Monitoring's feedback loop is also central to the idea of *Autonomic Computing* (AC), an architecture in which the system is capable of regulating itself and thus enabling self-management and self-healing. +
    AC was inspired by the operation of the human central nervous system. It draws an analogy between it and a complex, distributed information system. Unconscious processes, such as the control over the rate of breath, do not require human effort. The goal of AC is to minimize the need for human intervention in a similar way, by replacing it with self-regulation. Comprehensive monitoring can provide an effective means to achieve this end."
    ** le monitoring implique les *timeseries*

* Monitoring and observability : https://dzone.com/refcardz/getting-started-with-opentelemetry

* Observability : https://dzone.com/refcardz/full-stack-observability-essentials
    ** Observability is "the ability to understand the current state of a system using only its external outputs."
    ** l'article propose une différence entre observabilité et monitoring, et explique que l'observabilité est là pour augmenter le potentiel du monitoring

    ** "Monitoring is an action; a human or an automated process can do it if they know what signals to look for. It can generate alerts, provide insights, suggest actions, measure traffic or real-user activity, and warn when issues occur."
    ** "Observability, on the other hand, lets you understand why the problem occurred. It is an approach that enables teams to ask questions about the holistic state of a system."

Derrière cette notion de "feedback & monitoring", et même d'observabilité, il y a l'objectif de mieux comprendre l'application afin d'être capable d'anticiper, de prédire, son comportement futur, et de prévenir d'eventuels problèmes d'arriver.

* Feedback : Besoin de remonter les conséquences d'une action corrective : retour à la normale ou pas ?

== Schema resources

WARNING: I first designed this schema in 2017/02, and some of the below resources I used when creating it are available anymore.

* https://dzone.com/storage/assets/18140-Continuous-Delivery.pdf[DZone - The DZone guide to Continuous Delivery 2015]: p20/43
* https://dzone.com/storage/assets/17431-docker-jenkins-continuous-delivery.pdf[DZone - Docker / Jenkins - Continuous Delivery]: p15/18
* http://www.bogotobogo.com/DevOps/DevOps_CI_CD_Pipeline_Sample.php
* http://www.rightscale.com/blog/cloud-management-best-practices/continuous-integration-and-delivery-cloud-how-rightscale-does-it
* http://atginfo.com/demystifying-dev-ops-part-1/
* http://agilityladder.nl/it-value/continuous-delivery/: circular graph on Continuous Delivery

Ressources pour la description des phases du cycle DevOps : 

    * https://medium.com/taptuit/the-eight-phases-of-a-devops-pipeline-fda53ec9bba
        ** et pour la description des cycles Continuous Integration, Continuous Delivery, Continuous Deployment : +
        https://medium.com/taptuit/what-is-devops-fb3d044ef659
        
    * https://blog.hubspot.com/website/devops-pipeline

Explication de la Continuous Integration, Continuous Delivery et Continuous deployment

    * Continuous Integration : 
        ** https://aws.amazon.com/fr/devops/continuous-integration/
    * Continuous Delivery : 
        ** https://aws.amazon.com/fr/devops/continuous-delivery/
    * Continuous Deployment : 
        ** https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment
    * Wikipedia pour les 3
        ** https://en.wikipedia.org/wiki/Continuous_integration
        ** https://en.wikipedia.org/wiki/Continuous_delivery
        ** https://en.wikipedia.org/wiki/Continuous_deployment
    * https://www.redhat.com/fr/topics/devops/what-is-ci-cd
        ** pour la CI/CD, voir également la définition simple et efficace de https://fr.wikipedia.org/wiki/CI/CD

Explication sur le DevOps : 

    * https://medium.com/taptuit/what-is-devops-fb3d044ef659
    * https://www.atlassian.com/fr/devops
    * https://fr.wikipedia.org/wiki/Devops
    * https://aws.amazon.com/fr/devops/what-is-devops/
    * https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-devops/

